### ISSUE TITLE
`npm install`fails

### ISSUE THREAD

**Issue by JSomerstone** [pekkis/react-broilerplate-project#2]
```
sudo npm install
npm http GET https://registry.npmjs.org/dr-kobros/react-broilerplate-server-express
npm http GET https://registry.npmjs.org/axios
npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/classnames
npm http GET https://registry.npmjs.org/immutable
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/normalize.css
npm http GET https://registry.npmjs.org/react-fa
npm http GET https://registry.npmjs.org/dr-kobros/react-broilerplate
npm http 200 https://registry.npmjs.org/classnames
npm http GET https://registry.npmjs.org/classnames/-/classnames-2.2.3.tgz
npm http 200 https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz
npm http 200 https://registry.npmjs.org/axios
npm http GET https://registry.npmjs.org/axios/-/axios-0.9.1.tgz
npm http 200 https://registry.npmjs.org/normalize.css
npm http GET https://registry.npmjs.org/normalize.css/-/normalize.css-3.0.3.tgz
npm http 200 https://registry.npmjs.org/immutable
npm http GET https://registry.npmjs.org/immutable/-/immutable-3.7.6.tgz
npm http 200 https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/body-parser/-/body-parser-1.15.0.tgz
npm http 200 https://registry.npmjs.org/classnames/-/classnames-2.2.3.tgz
npm http 404 https://registry.npmjs.org/dr-kobros/react-broilerplate-server-express
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! command "node" "/bin/npm" "install"
npm ERR! cwd /home/vagrant/sync
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm http 200 https://registry.npmjs.org/body-parser/-/body-parser-1.15.0.tgz
npm http 200 https://registry.npmjs.org/normalize.css/-/normalize.css-3.0.3.tgz
npm http 200 https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz
npm http 200 https://registry.npmjs.org/axios/-/axios-0.9.1.tgz
npm http 200 https://registry.npmjs.org/immutable/-/immutable-3.7.6.tgz
npm http 200 https://registry.npmjs.org/react-fa
npm http 404 https://registry.npmjs.org/dr-kobros/react-broilerplate
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! command "node" "/bin/npm" "install"
npm ERR! cwd /home/vagrant/sync
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm http GET https://registry.npmjs.org/react-fa/-/react-fa-4.0.0.tgz
npm http 200 https://registry.npmjs.org/react-fa/-/react-fa-4.0.0.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/sync/npm-debug.log
npm ERR! not ok code 0
```

**Comment by pekkis** [comment]
Hi Joona!

npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6

The problem very probably lies in your ancient node.js and npm. Upgrade to a recent node and npm version 3 and you shall overcome!

I shall upgrade the README to also include npm version. I'm not sure whether any of this will work with npm version 1 or 2.
